# Generated by Django 5.1.15 on 2026-07-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('person', 'Person'), ('project', 'Project'), ('event', 'Event'), ('tag', 'Tag')], max_length=16)),
                ('subject_id', models.UUIDField()),
                ('predicate', models.CharField(max_length=64)),
                ('object_type', models.CharField(choices=[('person', 'Person'), ('project', 'Project'), ('event', 'Event'), ('tag', 'Tag')], max_length=16)),
                ('object_id', models.UUIDField()),
                ('confidence', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_type', 'subject_id'], name='knowledge_k_user_id_e5260a_idx'), models.Index(fields=['user', 'object_type', 'object_id'], name='knowledge_k_user_id_1e07a6_idx')],
            },
        ),
    ]
