# Generated by Django 5.1.15 on 2026-07-04 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task', 'Task'), ('conversation', 'Conversation'), ('workout', 'Workout'), ('meal', 'Meal'), ('mood', 'Mood'), ('meeting', 'Meeting'), ('idea', 'Idea'), ('habit_check', 'Habit check'), ('learning', 'Learning'), ('expense', 'Expense'), ('trip', 'Trip'), ('health', 'Health')], max_length=32)),
                ('occurred_at', models.DateTimeField(help_text='When it happened, not when it was logged.')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('importance', models.SmallIntegerField(default=3)),
                ('mood_valence', models.SmallIntegerField(blank=True, help_text='-2..+2 quick sentiment, if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='planned', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'occurred_at'], name='events_even_user_id_37084f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'type', 'occurred_at'], name='events_even_user_id_316a5c_idx'),
        ),
    ]
