# Generated by Django 5.1.15 on 2026-07-05 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('emotion', models.CharField(blank=True, default='', max_length=64)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(blank=True, choices=[('agreement', 'Agreement'), ('disagreement', 'Disagreement'), ('unresolved', 'Unresolved')], default='', max_length=16)),
                ('relationship_delta', models.SmallIntegerField(blank=True, help_text='-2..+2 change in relationship quality.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoodDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('label', models.CharField(max_length=64)),
                ('intensity', models.SmallIntegerField(help_text='1..5')),
                ('trigger', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('raw_text', models.TextField()),
                ('source', models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='text', max_length=8)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='source_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_events', to='events.journalentry'),
        ),
    ]
