# Generated by Django 5.1.15 on 2026-07-05 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_conversationdetail_mooddetail_journalentry_and_more'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='routine_occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilling_events', to='routines.routineoccurrence'),
        ),
    ]
