# Generated by Django 5.1.15 on 2026-07-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_conversationdetail_mooddetail_journalentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('schedule_rule', models.CharField(default='FREQ=DAILY', help_text='RRULE string. Only FREQ=DAILY and FREQ=WEEKLY;BYDAY=... are interpreted today — see occurrences.due_today().', max_length=255)),
                ('expected_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('fulfilling_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='routines.routine')),
            ],
            options={
                'ordering': ['-expected_date'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'expected_date'), name='unique_occurrence_per_day')],
            },
        ),
    ]
